name: Build and Push React Frontend

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'zorgmate-frontend/**'
      - '.github/workflows/ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: zorgmate-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check frontend folder contents
        run: ls -la

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: fays21/zorgmate-frontend:latest
          build-args: |
            REACT_APP_API_BASE_URL=/api
