name: Build and Push React Frontend

on:
  push:
    branches:
      - main
      - master
    paths:
      - '**'
      - '.github/workflows/frontend.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push multi-platform Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend-zorgmate
          push: true
          tags: fays21/zorgmate-frontend:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            REACT_APP_API_BASE_URL=/api
